package com.cristph.template.core.pojos.entity;


import com.cristph.template.core.pojos.dto.ManagerDTO;

public class Manager extends BaseEntity<ManagerDTO>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.power_id
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private Long accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.user_name
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.full_name
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.email
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.tel
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.max_logon_num
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private Integer maxLogonNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.ip
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mac
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.ip_mac
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String ipMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.status
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private String status;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.operator_type
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    private Integer operatorType;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.power_id
     *
     * @return the value of manager.power_id
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public Long getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.power_id
     *
     * @param accessId the value for manager.power_id
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setAccessId(Long accessId) {
        this.accessId = accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.user_name
     *
     * @return the value of manager.user_name
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.user_name
     *
     * @param userName the value for manager.user_name
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.full_name
     *
     * @return the value of manager.full_name
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.full_name
     *
     * @param roleName the value for manager.full_name
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName=roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.email
     *
     * @return the value of manager.email
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.email
     *
     * @param email the value for manager.email
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.tel
     *
     * @return the value of manager.tel
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.tel
     *
     * @param tel the value for manager.tel
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.max_logon_num
     *
     * @return the value of manager.max_logon_num
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public Integer getMaxLogonNum() {
        return maxLogonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.max_logon_num
     *
     * @param maxLogonNum the value for manager.max_logon_num
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setMaxLogonNum(Integer maxLogonNum) {
        this.maxLogonNum = maxLogonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.ip
     *
     * @return the value of manager.ip
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.ip
     *
     * @param ip the value for manager.ip
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mac
     *
     * @return the value of manager.mac
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mac
     *
     * @param mac the value for manager.mac
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.ip_mac
     *
     * @return the value of manager.ip_mac
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getIpMac() {
        return ipMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.ip_mac
     *
     * @param ipMac the value for manager.ip_mac
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setIpMac(String ipMac) {
        this.ipMac = ipMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.status
     *
     * @return the value of manager.status
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.status
     *
     * @param status the value for manager.status
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.operator_type
     *
     * @return the value of manager.operator_type
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public Integer getOperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.operator_type
     *
     * @param operatorType the value for manager.operator_type
     *
     * @mbggenerated Tue Aug 15 11:03:51 CST 2017
     */
    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

}